name: Deploy to Github Pages

# Event - workflow triggers when we push to the 'main ' branch  
on:

  push:
    branches: [ main ]

  workflow_dispatch: 

#Gives jobs permission to clone the repo and create a page deployment  

permissions:
  contents: read
  pages: write
  id-token: write


job: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Checkout repository using git
      uses: actions/checkout@v3
    - name: Install, build and upload site
      uses: withastro/action@v1

  deploy: 
    needs: build 
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy to Github Pages
      id: deployment
      uses: actions/deploy-pages@1

  

