name: Deploy to vercel 

on: 
  push:
     branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}



jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    steps:
    - name: checkouts git repo
    - uses: actions/checkout@v2
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Envionment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN}}
    - name: Deploy Project to Vercel 
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}


